### ISSUE TITLE
[PE-D][Tester D] Listing will only have the date field if both start date and end date is input

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T13-2/tp#103]
How to reproduce?
1. `add -n DBS -t Software Engineer -e dbs@example.com -d2 2024-05-05`
2. Listing is added, but date is not reflected even though there is an end date

Potential Problems:
User may be unaware of potential deadlines. Perhaps can make the listings reflect dates if there is minimally a deadline.

![Screenshot 2024-04-05 at 4.52.01 PM.png](https://raw.githubusercontent.com/bertrandong/ped/main/files/ff73bda4-81f3-4bcb-8c2d-c8d52152753b.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: bertrandong/ped#4

**Comment by AjayArvind2207** [comment]
Similar to #115
