### ISSUE TITLE
[PE-D][Tester D] Add function currently allows dates that have already passed as inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T13-2/tp#97]
How to reproduce?
1. `add -n DBS -t Software Engineer -e dbs@example.com -d1 2023-04-04 -d2 2023-05-05`

Potential Problems:
- Users may be looking at data that is no longer relevant for them

![Screenshot 2024-04-05 at 4.41.22 PM.png](https://raw.githubusercontent.com/bertrandong/ped/main/files/41e6a9af-5cbe-4365-abce-4ee0ac0e46ce.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: bertrandong/ped#3

**Comment by AjayArvind2207** [comment]
Similar to #130
